### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by laidig** [BusTechnology/gtfs_calendar_editor#1]
https://travis-ci.org/

It's easy, it's free, it's good.

**Comment by willwong430** [comment]
In deploying with Travis-CI, several issues arose. The issue with the relative path was solved by forcing all the modules into the 'tests/' directory. This was achieved by copying the modules into the directory before running the tests. The next issue was PyPI cloned an older version of mzgtfs. This was solved by forcing the requirements.txt file to clone from the latest release candidate. The final issue also stemmed from an misunderstanding of the requirements.txt and setup.py files. The requirements.txt stipulates the concrete dependencies whereas the setup.py file denotes the abstract dependencies. (Good read here: https://caremad.io/posts/2013/07/setup-vs-requirement/)
